site_name: STS Reader
site_description:
  The documentation for STS/STM readers that converts STS/STM experimental files according to NXsts definition.
site_author: "The FAIRmat authors"
site_url: ""
use_directory_urls: false
nav:
  - Home: 
      - index.md
  - Explanation: 
      - explanation/reader-explanation.md
  - Tutorial:
      - tutorial/nomad-tutorial.md
      - tutorial/reader-tutorial.md
  - How-To-Guide : 
      - how-to-guides/how-to-interact-with-reader.md
  - Reference: 
      - reference/reference.md
plugins:
  # - mkdocstrings
  # - mermaid2
  - search
  - macros:
      module_name: docs/macros
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
use_directory_urls: false
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
# theme:
#   name: "material"
#   features:
#   - navigation.tabs
#   - navigation.sections
#   - navigation.top
#   - navigation.bottom
#   - toc.integrate
#   - search.suggest
#   - search.highlight
#   - content.tabs.link
#   - content.tabs.copy
#   - content.code.annotation
  # icon:
  #   admonition:
  #     note: octicons/tag-16
extra_css:
  - stylesheets/extra.css