site_name: STS Reader docs
site_description:
  The documentation for STS/STM readers that converts STS/STM experimental files into NXsts definition.
site_author: "The FAIRmat authors"
site_url: ""
use_directory_urls: false
nav:
  - Home: index.md
  # - Tutorial: tutorials.md
  - How-To-Guide : how_to_guide.md
  # - Reference: references.md
  # - Explanation: explanations.md
plugins:
  - mkdocstrings
  - mermaid2
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: "material"
  feature:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - navigation.bottom
  - toc.integrate
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.tabs.copy
  - content.code.annotation
  icon:
    admonition:
      note: octicons/tag-16
extra_css:
  - stylesheets/extra.css