name: pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UV_SYSTEM_PYTHON: true
  
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python ${{matrix.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install nomad
        if: "${{ matrix.python_version != '3.8'}}"
        run: |
          uv pip install nomad-lab[infrastructure]@git+https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git
      - name: Install package and dependencies
        run: |
          uv pip install ".[dev]"
      - name: Test pynxtools data conversion
        run: |
          pytest tests/test_reader.py
      - name: Test Nomad Examples
        if: "${{ matrix.python_version != '3.8'}}"
        run: |
          pytest tests/test_nomad_examples.py
